spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebatecnicatrinity
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
server:
  port: 8080